---
kind: Service
apiVersion: v1
metadata:
  name: ${IMAGE_NAME}-service
  namespace: default
  labels:
    k8s-app: ${IMAGE_NAME}
    role: "${BUILD_NUMBER}"
spec:
  ports:
  - name: ${IMAGE_NAME}e-service
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    k8s-app: ${IMAGE_NAME}
  type: LoadBalancer
