# Description
# ===========
# This playbook build the sample application and deploy it into VM

- hosts: localhost
  vars_files:
  - vm_vars.yml

  tasks:   
    - include: get_vm_host.yml

    - include: get_dbtoken.yml

    - name: Removing
      file:
        path: "{{ workspace }}"
        state: absent

    - name: Git Clone sample app
      git:
        repo: "{{ repo_url }}"
        dest: "{{ workspace }}"

    - name: update uri
      lineinfile:
        dest: "{{ workspace }}/src/main/resources/application.properties"
        regexp: '^azure.cosmosdb.uri='
        line: "{{ dburi }}"

    - name: update key
      lineinfile:
        dest: "{{ workspace }}/src/main/resources/application.properties"
        regexp: '^azure.cosmosdb.key='
        line: "{{ dbkey }}"

    - name: update db name
      lineinfile:
        dest: "{{ workspace }}/src/main/resources/application.properties"
        regexp: '^azure.cosmosdb.database='
        line: "{{ dbstring }}"

    - name: Build sample app
      shell: mvn package chdir="{{ workspace }}"

- name: Install JRE
  hosts: vmhost
  become: yes
  vars_files:
  - vm_vars.yml

  tasks:
  - name: Install JRE
    apt:
      name: default-jre
      update_cache: yes

  - name: Copy app to Azure VM
    copy:
      src: "{{ workspace }}/target/todo-app-java-on-azure-1.0-SNAPSHOT.jar"
      dest: "/home/{{ admin_username }}/app.jar"
      force: yes
      mode: 0755

  - name: Start the app
    shell: java -jar "/home/{{ admin_username }}/app.jar" --server.port=8080 >/dev/null 2>&1 &
    async: 5000
    poll: 0

